baseURL = 'https://milalaveo.com/'
languageCode = 'en-us'
email = 'bloolya@gmail.com'
title = 'Milalaveo'
theme = 'milalaveo'
description = 'Lolita Malaeva portfolio'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'Projects'
    url = '/projects'
    weight = 20
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 30
[[menu.main]]
    name = 'Contact'
    url = '/contact'
    weight = 40
[[menu.footer]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/lolita-malaeva-72b480227/'
    weight = 10
[[menu.footer]]
    name = 'GitHub'
    url = 'https://github.com/milalaveo'
    weight = 20