baseURL = 'https://milalaveo.com/'
languageCode = 'en-us'
title = 'Milalaveo'
theme = 'milalaveo'
sectionPagesMenu = "main"

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 30
[[menu.main]]
    name = 'Contact'
    url = '/contact'
    weight = 40
[[menu.footer]]
    name = 'LinkedIn'
    url = 'https://linkedin.com'
    weight = 10
[[menu.footer]]
    name = 'GitHub'
    url = 'https://github.com/milalaveo'
    weight = 20